library(tibble)

GTex_to_gganato = 
  tribble(
    ~tissue_type, ~organ,
    "Adipose - Subcutaneous","adipose_tissue",
    "Adipose - Visceral (Omentum)","adipose_tissue",
    "Adrenal Gland","adrenal_gland",
    "Artery - Aorta","aorta",
    "Artery - Coronary","coronary_artery",
    "Artery - Tibial",NA,
    "Bladder","urinary_bladder",
    "Brain - Amygdala","amygdala",
    "Brain - Anterior cingulate cortex (BA24)","brain",
    "Brain - Caudate (basal ganglia)","brain",
    "Brain - Cerebellar Hemisphere","cerebellar_hemisphere",
    "Brain - Cerebellum","cerebellum",
    "Brain - Cortex","prefrontal_cortex",
    "Brain - Frontal Cortex (BA9)","frontal_cortex",
    "Brain - Hippocampus","hippocampus",
    "Brain - Hypothalamus","brain",
    "Brain - Nucleus accumbens (basal ganglia)","brain",
    "Brain - Putamen (basal ganglia)","brain",
    "Brain - Spinal cord (cervical c-1)","spinal_cord",
    "Brain - Substantia nigra","brain",
    "Breast - Mammary Tissue","breast",
    "Cervix - Ectocervix","ectocervix",
    "Cervix - Endocervix","uterine_cervix",
    "Colon - Sigmoid","colon",
    "Colon - Transverse","colon",
    "Esophagus - Gastroesophageal Junction","esophagus",
    "Esophagus - Mucosa","esophagus",
    "Esophagus - Muscularis","esophagus",
    "Fallopian Tube","fallopian_tube",
    "Heart - Atrial Appendage","heart",
    "Heart - Left Ventricle","heart",
    "Kidney - Cortex","kidney",
    "Liver","liver",
    "Lung","lung",
    "Minor Salivary Gland","salivary_gland",
    "Muscle - Skeletal","skeletal_muscle",
    "Nerve - Tibial","nerve",
    "Ovary","ovary",
    "Pancreas","pancreas",
    "Pituitary","pituitary_gland",
    "Prostate","prostate",
    "Skin - Not Sun Exposed (Suprapubic)","skin",
    "Skin - Sun Exposed (Lower leg)","skin",
    "Small Intestine - Terminal Ileum","small_intestine",
    "Spleen","spleen",
    "Stomach","stomach",
    "Testis","testis",
    "Thyroid","thyroid_gland",
    "Uterus","uterus",
    "Vagina","vagina",
    "Whole Blood",NA
  ) %>%
  write_rds(here('GTEx/GTEx_tissue_to_gganato.rds'))
